spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: curso
    password: admin123

    jpa:
      hibernate:
        ddl-auto: update
        show-sq: true
        properties:
          hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.Oracle10gDialect
